### ISSUE TITLE
README.md にオンラインブックへのリンクを追加

### ISSUE THREAD

**Issue by AstroMev** [bigen1925/introduction-to-web-application-with-python#1]
# どの箇所をもっと良く出来ますか？

< 誤植箇所や、ソースコードの改善点などについて、具体的な箇所を教えて下さい。 >
- README.md にオンラインブックへのリンクが無い

# どのように良く出来ますか？

<どのように修正すると、より良くなるか教えて下さい>
- README.md にオンラインブックへの [リンク](https://zenn.dev/bigen1925/books/e6c9492a82f5e2e10fca) を追加

# 変更すると、なぜ良くなりますか？

<変更したほうが良いと思う理由を教えて下さい>
- このリポジトリからオンラインブックに移動しやすい

**Comment by bigen1925** [comment]
@AstroMev 
ご指摘ありがとうございます！
PRもありがとうございます。

おっしゃる通りですので、修正します。

**Comment by bigen1925** [comment]
solved by https://github.com/bigen1925/python_web_application_for_3rd_year_engineer/pull/2
