### ISSUE TITLE
Chapter14 でマークダウンのずれがある

### ISSUE THREAD

**Issue by uenoka** [bigen1925/introduction-to-web-application-with-python#11]
# どの箇所をもっと良く出来ますか？

動的、静的の説明の以下の箇所でマークダウンのハイライトにずれがありました。
> これを **「動的なHTMLの生成」 （あるいは ** 「動的なレスポンスの生成」）と呼びます。

# どのように良く出来ますか？

下記のように動的、静的を対比する形に変更する。

> これを **「動的なHTMLの生成」**  （あるいは **「動的なレスポンスの生成」** ）と呼びます。

**Comment by bigen1925** [comment]
ありがとうございます！

もし次回以降またご協力頂ける際、PRを提出していただける場合は、Issueはなくても問題ありません。

 @uenoka

**Comment by uenoka** [comment]
PRのみで大丈夫とのこと了解です！
@bigen1925
