### ISSUE TITLE
Chapter 15 で、扱う対象にしているPOST パラメーターの記載が異なる？

### ISSUE THREAD

**Issue by uenoka** [bigen1925/introduction-to-web-application-with-python#13]
# どの箇所をもっと良く出来ますか？

multipart/form-dataに対応する のセクション

# どのように良く出来ますか？
multipart/form-data ではなく application/x-www-form-urlencoded に変更する。

# 変更すると、なぜ良くなりますか？

「multipart/form-dataに対応する」と記載がありますが、その後の流れを見ると application/x-www-form-urlencoded を扱っているようなので、意図しているのは application/x-www-form-urlencoded だと思われます。（「ちなみに、multipart/form-data形式で送られてきた内容をパースするには、pythonではcgiモジュールのFieldStorageというクラスを利用します。 」等の記載より）

**Comment by bigen1925** [comment]
Thank you!

**Comment by bigen1925** [comment]
https://github.com/bigen1925/introduction-to-web-application-with-python/pull/12
