### ISSUE TITLE
importが記載通りに進めたはずですが動きません。

### ISSUE THREAD

**Issue by soundofhorizon** [bigen1925/introduction-to-web-application-with-python#22]
# どの箇所をもっと良く出来ますか？
https://zenn.dev/bigen1925/books/introduction-to-web-application-with-python/viewer/modulize

< 誤植箇所や、ソースコードの改善点などについて、具体的な箇所を教えて下さい。 >

import socket

from henango.server.worker import Worker

class Server:
    """
    Webサーバーを表すクラス
    """

    # ...
    
STEP2において、importにてエラーを吐いています。

# どのように良く出来ますか？

<どのように修正すると、より良くなるか教えて下さい>

以下のようにするとうまく動きました。しかし直感的に大丈夫なのか心配です。

from ...henango.server.worker import Worker
↑上位ディレクトリを参照しているためこのような書き方をしています。

私が間違えている可能性があります。なぜ上位ディレクトリで同じようなimportができているのかがわかりませんでした。

**Comment by soundofhorizon** [comment]
申し訳ございません。
IDEAの独自的なエラーでした。実行したら治りました。

**Comment by bigen1925** [comment]
進めたようで良かったです :)

また分からない事があればお気軽にお聴きください。
