### ISSUE TITLE
Chapter 08のタイポと思われる箇所修正

### ISSUE THREAD

**Issue by yasuaki640** [bigen1925/introduction-to-web-application-with-python#23]
お世話になっております。素晴らしい本を読ませていただいております。

# どの箇所をもっと良く出来ますか？

zenn独自のmd記法[`::: message`](https://zenn.dev/zenn/articles/markdown-guide#%E3%83%A1%E3%83%83%E3%82%BB%E3%83%BC%E3%82%B8)を使用している箇所に[正しく描画されていないと思われる箇所](https://zenn.dev/bigen1925/books/introduction-to-web-application-with-python/viewer/making-silly-web-server-step4#:~:text=%E8%A1%8C%E7%9B%AE%E3%81%A7%E3%81%99%E3%80%82-,%3A%3A%3A%20messages,-Zenn%E3%81%A7%E3%81%AF%E3%82%BD%E3%83%BC%E3%82%B9)を発見しました。

調査したところローカルのプレビュー表示では`::: message`でも正しく表示されますが`zenn.dev`上では正しく表示されないようです。
[※スクラップで確認してみました。](https://zenn.dev/y640/scraps/97bff473713fd2)

# どのように良く出来ますか？

`::: messages` -> `::: message`に修正すると良いかと思います。

# 変更すると、なぜ良くなりますか？

見栄えの向上

**Comment by bigen1925** [comment]
@yasuaki640 
本書を読んでいただきありがとうございます :)

指摘修正、ありがとうございます！

反映させていただきました。
