### ISSUE TITLE
Zenn の本文をリポジトリ内に入れることは出来ないのでしょうか？

### ISSUE THREAD

**Issue by AstroMev** [bigen1925/introduction-to-web-application-with-python#3]
# どの箇所をもっと良く出来ますか？

< 誤植箇所や、ソースコードの改善点などについて、具体的な箇所を教えて下さい。 >
- Zenn の仕様を完全に理解できていないのですが、修正提案のためにリポジトリ内に本文を置くことは出来ないのでしょうか？

# どのように良く出来ますか？

<どのように修正すると、より良くなるか教えて下さい>
- 本文をリポジトリ内に追加

# 変更すると、なぜ良くなりますか？

<変更したほうが良いと思う理由を教えて下さい>
- 本文の修正提案がこの Issue で可能になる

**Comment by bigen1925** [comment]
@AstroMev 
なるほど、提案ありがとうございます。

単に自分一人で書くには困ることがなかったのでGit管理してなかったのですが、修正提案いただけるようであればリポジトリに乗せてしまったほうがよさそうですね。

少しZennの仕様を読んで検討してみます。

**Comment by bigen1925** [comment]
@AstroMev 
書籍をGit管理するようにしました。

https://github.com/bigen1925/introduction-to-web-application-with-python/tree/main/books

Git管理するようになるとURLにslugを使えるようなので、URLもお引越ししました。

提案ありがとうございました。

**Comment by AstroMev** [comment]
@bigen1925 
お手数をお掛けしてしまいすみません。
貴重な資料をありがとう御座います。有効に活用させて頂きます！
