### ISSUE TITLE
Chapter15のソースコード(study/workerthread.py)の表示が１行のみになっている。

### ISSUE THREAD

**Issue by mori0120** [bigen1925/introduction-to-web-application-with-python#37]
# Chapter 15 -> POSTリクエストを送信し、ボディを観察してみる。-> ソースコード

githubへのリンクでstudy/workerthread.pyのコードを表示されていますが、169行目の１行のみの表示になっているため、表示範囲を全体(1から200行目まで)とする方が良いと思います。

**Comment by bigen1925** [comment]
@mori0120 
ありがとうございます :)

修正しました。 #38
