### ISSUE TITLE
Chapter12の変数名に誤りがある

### ISSUE THREAD

**Issue by selfsryo** [bigen1925/introduction-to-web-application-with-python#7]
お世話になっております。
素晴らしいコンテンツを提供していただきありがとうございます。
普段Djangoを使っていますが、フレームワークの仕組みを体系的に学びたくなり勉強させていただいております。

# どの箇所をもっと良く出来ますか？
< 誤植箇所や、ソースコードの改善点などについて、具体的な箇所を教えて下さい。 >
以下見出しの**88-96行目**のサンプルコード内の変数名に誤植があります。
（**mine_type**ではなく、**content_type**になっている）
https://zenn.dev/bigen1925/books/introduction-to-web-application-with-python/viewer/daemonize#%E3%82%BD%E3%83%BC%E3%82%B9%E3%82%B3%E3%83%BC%E3%83%89-2

ご確認お願いいたします。

**Comment by bigen1925** [comment]
@selfsryo 
ご指摘ありがとうございます！

> 素晴らしいコンテンツを提供していただきありがとうございます。

フィードバックありがとうございます。
めちゃくちゃ励みになります！

こちらはソースコードが`mime_type`となっているのが間違い（`content_type`が正しい）だったため、ソースコードを修正しました ;-)
https://github.com/bigen1925/introduction-to-web-application-with-python/commit/1256eb689b1e17635ec30e5f6f017c4bfe7b5a2a
