### ISSUE TITLE
Chapter9の Cookie の箇所に誤植がある

### ISSUE THREAD

**Issue by uenoka** [bigen1925/introduction-to-web-application-with-python#9]
# どの箇所をもっと良く出来ますか？

Chapter9 の HTTP とは？のセクションで3段落目には `Cookieはhogeを使う。` と記載されていますが、その後のクライアント 1, 2 で `Cookieはfugaね` , `cookie=fuga`  となっています。

# どのように良く出来ますか？
3段落目の「Cookieはhogeを使う」 -> 「Cookieはfugaを使う」

# 変更すると、なぜ良くなりますか？

検索ワードが hoge, Cookie が fuga と、別のものを使用すると想定しているかと思うため。

**Comment by bigen1925** [comment]
@uenoka 
ありがとうございます！

後ほど確認して修正しておきます 👍

**Comment by uenoka** [comment]
@bigen1925 
ありがとうございます。  
ちなみに、Issue ではなくプルリクを出すのはアリでしょうか？  
（ちょうど読みながら進めているのでむしろプルリク出す方がいいのかと思ったもののREADMEにはIssueの記載しかなかったので質問しました。）

**Comment by bigen1925** [comment]
もちろん大歓迎です！
@uenoka

**Comment by uenoka** [comment]
@bigen1925 
プルリク出しました！

**Comment by bigen1925** [comment]
@uenoka 
ご協力ありがとうございます、マージさせていただきました！ XD

**Comment by uenoka** [comment]
こちらこそ、いいコンテンツありがとうございます！
